import type { BoatState } from "@/types"

export const demoBoats: BoatState[] = [
  {
    boat_id: "boat-001",
    name: "Sea Wanderer",
    weight_class: "light",
    gps_lat: 44.27,
    gps_lon: -68.78,
    heading: 45,
    timestamp: Date.now(),
    image: "/demo-sighting.jpg",
  },
  {
    boat_id: "boat-002",
    name: "Lobster King",
    weight_class: "heavy",
    gps_lat: 44.15,
    gps_lon: -68.65,
    heading: 120,
    timestamp: Date.now(),
    image: "/demo-sighting.jpg",
  },
  {
    boat_id: "boat-003",
    name: "Tide Runner",
    weight_class: "light",
    gps_lat: 44.32,
    gps_lon: -68.92,
    heading: 200,
    timestamp: Date.now(),
    image: "/demo-sighting.jpg",
  },
  {
    boat_id: "boat-004",
    name: "Atlantic Scout",
    weight_class: "heavy",
    gps_lat: 44.1,
    gps_lon: -68.55,
    heading: 310,
    timestamp: Date.now(),
    image: "/demo-sighting.jpg",
  },
  {
    boat_id: "boat-005",
    name: "Harbor Breeze",
    weight_class: "light",
    gps_lat: 44.38,
    gps_lon: -68.72,
    heading: 85,
    timestamp: Date.now(),
    image: "/demo-sighting.jpg",
  },
  {
    boat_id: "boat-006",
    name: "Deep Current",
    weight_class: "heavy",
    gps_lat: 44.22,
    gps_lon: -68.88,
    heading: 160,
    timestamp: Date.now(),
    image: "/demo-sighting.jpg",
  },
]
